openapi: 3.0.4
info:
  contact:
    email: support@apibricks.io
    name: API BRICKS LTD
    url: https://www.coinapi.io
  license:
    name: MIT License
    url: https://github.com/api-bricks/api-bricks-sdk/blob/master/LICENSE
  title: CoinAPI Indexes REST API
  version: v1
servers:
- url: https://rest-api.indexes.coinapi.io
security:
- APIKey: []
- JWT: []
paths: {}
components:
  schemas: {}
  securitySchemes:
    APIKey:
      description: API Key is required to access the endpoints
      in: header
      name: Authorization
      type: apiKey
    JWT:
      bearerFormat: JWT
      description: "JWT Authorization header using the Bearer scheme. Example: \"\
        Bearer {token}\""
      scheme: bearer
      type: http
