name: Publish CoinAPI Market Data API REST package
on:
  release:
    types: [created]
  push:
    branches:
      - master
    paths:
      - 'coinapi/market-data-api-rest/sdk-handcrafted/java-rest/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coinapi/market-data-api-rest/sdk-handcrafted/java-rest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Publish to GitHub Packages
        run: mvn -B deploy -DskipTests || exit 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
