name: Publish CoinAPI Market Data API REST package
on:
  release:
    types: [created]
  push:
    branches:
      - master
    paths:
      - 'coinapi/market-data-api-rest/sdk-handcrafted/python-rest/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coinapi/market-data-api-rest/sdk-handcrafted/python-rest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'
          
      - name: install
        run: python -m pip install --user --upgrade setuptools wheel twine
       
      - name: setup package
        run: python setup.py sdist bdist_wheel
        
      - name: deploy
        run: python -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }} || exit 0
        
