name: CoinAPI Indexes API REST OpenAPI to SDK

on:
  push:
    branches:
      - master # Adjust to your default branch (e.g., main) if different
    paths:
      - 'coinapi/indexes-api-rest/spec/openapi.json'
  pull_request:
    branches:
      - master # Adjust to your default branch (e.g., main) if different
    paths:
      - 'coinapi/indexes-api-rest/spec/openapi.json'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-openapi-to-sdk.yaml
    with:
      product_line_slug: "coinapi"
      api_type_slug: "indexes-api-rest"
      commit_message_subject: "CoinAPI Indexes API REST Historical"
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
