name: Publish Python SEC API SDK to PyPI

on:
  push:
    branches:
      - master # Or your primary branch name
    paths:
      - 'finfeedapi/sec-api/sdk/python/**' # Watch for changes in the Python SDK directory

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: finfeedapi/sec-api-rest/sdk/python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools twine

      - name: Build package distributions
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: deploy
        run: python -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }} || exit 0